server:
  port: 8080

spring:
  application:
    name: e-tender

#cassandra:
#  contact-points: 127.0.0.1
#  port: 9042
#  keyspace-name: ocds
#  username: cassandra
#  password: cassandra

ocds.prefix: ocds-t1s2t3