server:
  port: 8080

spring:
  application:
    name: e-access

cassandra:
  contact-points: 127.0.0.1
  keyspace-name: ocds
  port: 9042
  username: cassandra
  password: cassandra

ocds:
  prefixes:
    main: ocds-t1s2t3
    test: test-t1s2t3
