package com.ocds.etender.model.dto.notice;

import lombok.Data;

@Data
public class Notice {//todo added from file doc
    public Boolean electronicAuctionWillBeUsed;
    public String electronicAuctionDate;
    public String additionalInformationAboutElectronicAuction;
    public Integer numberOfContractingAuthorities;
    public Boolean contractIsDividedIntoLots;
    public Integer quantityOfLots;
    public String contractingAuthorityReservesTheRightToAwardContracts;
    public Integer numberOfTenderers;
    public Integer minNumberOfCandidatesToBeInvited;
    public Integer maxNumberOfCandidatesToBeInvited;
    public Integer envisagedNumberOfCandidatesToBeInvited;
    public String objectiveCriteriaForChoosingTheLimitedNumberOfCandidates;
    public Boolean contractIsAwardedByACentralPurchasingBody;
    public Boolean procurementDocumentsAreAvailableForUnrestrictedAndFullDirectAccess;
    public String additionalInformationCanBeObtainedFrom;
    public String linkToTheCommunicationPage;
    public Boolean procurementIsCoveredByTheGovernmentProcurementAgreement;
    public String timeLimitForReceiptOfTendersOrRequests;
    public String languagesInWhichTendersOrRequestsToParticipateMayBeSubmitted;
    public String estimatedDateOfDispatchOfInvitationsToTenderOrToParticipateToSelectedCandidates;
    public Boolean recourseToStagedProcedureToGraduallyReduceTheNumberOfSolutionsToBeDiscussedOrTendersToBeNegotiated;
    public Boolean contractingAuthorityReservesTheRightToAwardTheContract;
    public String minimumTimeFrameDuringWhichTheTendererMustMaintainTheTender;
    public String tenderMustBeValidUntil;
    public Integer durationInMonths;
    public String conditionForTendersDate;
    public String conditionForTendersLocalTime;
    public String conditionForTendersPlace;
    public String conditionForTendersInformation;
    public Boolean economicAndFinancialStanding;
    public Boolean technicalAndProfessionalAbility;
    public Boolean contractIsReservedToShelteredWorkshopsAndEconomicOperators;
    public Boolean executionOfTheContractIsRestrictedToTheFramework;
    public String executionOfTheServiceIsReservedToAParticularProfession;
    public String contractPerformanceConditions;
    public Boolean obligationToIndicateTheNamesAndProfessionalQualificationsOfTheStaff;
    public String additionalInformation;
    public String reviewBodyLegalName;
    public String reviewBodyCountryName;
    public String reviewBodyLocality;
    public String reviewBodyStreetAddress;
    public String reviewBodyPostalCode;
    public String reviewBodyTelephone;
    public String reviewBodyFax;
    public String reviewBodyEmail;
    public String reviewBodyURL;
    public String bodyResponsibleLegalName;
    public String bodyResponsibleCountryName;
    public String bodyResponsibleLocality;
    public String bodyResponsibleStreetAddress;
    public String bodyResponsiblePostalCode;
    public String bodyResponsibleTelephone;
    public String bodyResponsibleFax;
    public String bodyResponsibleEmail;
    public String bodyResponsibleURL;
    public String preciseInformationOnDeadline;
    public String serviceLegalName;
    public String serviceCountryName;
    public String serviceLocality;
    public String serviceStreetAddress;
    public String servicePostalCode;
    public String serviceTelephone;
    public String serviceFax;
    public String serviceEmail;
    public String serviceURL;
    public String typeOfTheContractingAuthority;
    public String mainGeneralActivity;
    public Boolean buyerIsACentralPurchasing;
    public String NUTSCode;
}
